server-name: main
eshost: localhost
esport: 9200
esuser: mc_server
espass: password
debug: false
es-x-security: true
track-sessions: false
messages:
    permission-message: "&c > You do not have permission to perform this command. If you believe this is in error please contact your server administrator"
    player-not-found: "&c > Error: That player wasn't found! Try their actual minecraft name instead of nickname"
    